config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :items
  resources :pages

end

app/models/item.rb
class Item < ActiveRecord::Base

	validates :name, presence: true,
					 length: {  minimum: 3 }
	validates :adress, presence: true
	# validates :image, presence: true


	mount_uploader :image, ImageUploader


end

app/models/page.rb
class Page < ActiveRecord::Base

	validates :title, presence: true,
					 length: {  minimum: 5 }
	validates :content, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!


  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :adress, :description, :tag, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # aouter un champ ppour sélectionner
  # enumerateur
  # select pour choisir le type de page : accueil, FAQ, legal...


  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:title, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/items/_form.html.erb
<%= form_for @item, :html => {:multipart => true} do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Quel objet", class: "required" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :adress, "Où se trouve-t-il ?", class: "required" %><br>
    <%= f.text_field :adress %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :Image, class: "required" %><br>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h2>Editing item</h2>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h2>Listing items</h2>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Adress</th>
      <th>Description</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%#= image_tag(@item.image_url) if @item.image? %></td>
        <td><%= item.name %></td>
        <td><%= item.adress %></td>
        <td><%= item.description %></td>
        <td><%= item.tag %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h2>New item</h2>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @item.name %></h2>

<div style='width: 800px;'>
 	<div class="map" id="map" style='width: 800px; height: 400px;'></div>
</div>

<p>
  <strong>Adress:</strong>
  <%= @item.adress %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @item.tag %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@item.image_url) if @item.image? %>
</p>



<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>



<script type="text/javascript">
	

	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	markers = handler.addMarkers([
	  {
	    "lat": 0,
	    "lng": 0,
	    "picture": {
	      "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
	      "width":  36,
	      "height": 36
	    },
	    "infowindow": "hello!"
	  }
	]);
	handler.bounds.extendWith(markers);
	handler.fitMapToBounds();
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Encombrants</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  
</head>
<body>

<h1>Encombants</h1>


<%= render :partial => 'users/loginbar'  %>
<%= yield %>



</body>
</html>

app/views/pages/_form.html.erb
<%= form_for @page do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h2>Editing Page</h2>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h2>Admin des Pages</h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h2>New Page</h2>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb

<h2><%= @page.title %></h2>

<p>
	<%= @page.content %>	
</p>

app/views/users/_login.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
	<div><%= f.label :email %><br />
	<%= f.email_field :email, autofocus: true %></div>

	<div><%= f.label :password %><br />
	<%= f.password_field :password, autocomplete: "off" %></div>

	<% if devise_mapping.rememberable? -%>
	<div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
	<% end -%>
	<div><%= f.submit "Sign in" %></div>
<% end %>

app/views/users/_loginbar.html.erb

<% if user_signed_in? %>
	Welcome <%= current_user %> !
	<a href="#">Deconnexion</a>
<% else %>
	<% # todo : ne pas afficher cette partie si on est dans les pages item (autentification obligatoire, du coup on a 2 forms de connexion) %>

	<% # lien de login %>
	
	<p>Sign in</p>
	<%= render :partial => 'users/login'  %>

	<a href="#">or signup</a>

<% end %>


